version: '3'

services:

############################
# setup server container
############################
  server:
    build: ./server
    
    container_name: gravity-server
    
    expose:
      - ${APP_SERVER_PORT}
    
    environment: 
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    
    ports: 
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}

    volumes:
      - ./server/routes:/srv/app/server/routes
      - ./server/models:/srv/app/server/models
      - ./server/app.js:/srv/app/server/app.js
    
    networks:
      - db-server
      - client-server

    command: npm run start

  db:
    image: neo4j:latest
    
    container_name: gravity-neo4j
    
    expose: 
      - ${NEO4J_BROWSER_PORT}
    
    environment:
      - NEO4J_BROWSER_PORT=${NEO4J_BROWSER_PORT}
      - NEO4J_SERVER_PORT=${NEO4J_SERVER_PORT}
      - NEO4J_AUTH=none
      - NEO4J_dbms_logs_query_enabled=INFO
      - NEO4J_dbms_directories_import=import
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes    
      - NEO4J_dbms_logs_http_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc
    ports:
      - ${NEO4J_BROWSER_PORT}:${NEO4J_BROWSER_PORT}
      - ${NEO4J_SERVER_PORT}:${NEO4J_SERVER_PORT}
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    
    networks:
      - db-server

############################
# setup client container
############################
  client:
    build: ./client

    container_name: gravity-client
    # environment: 
    #   - REACT_APP_PORT=REACT_APP_PORT
    expose:
      - ${REACT_APP_PORT}
    
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    
    volumes: 
      - ./client/src:/srv/app/client/src
      - ./client/public:/srv/app/client/public
    
    networks:
      - client-server
    command: npm run start

networks:
  client-server:
    driver: bridge
  
  db-server:
    driver: bridge