export const ADD_DATA_NODE = "ADD_DATA_NODE";

export const ADD_DATA_EDGE = "ADD_DATA_EDGE";

export const REMOVE_SUBGRAPH_FROM_NODES = "REMOVE_SUBGRAPH_FROM_NODES";

export const REMOVE_DATA_NODE = "REMOVE_DATA_NODE";

export const REMOVE_DATA_EDGES = "REMOVE_DATA_EDGES";

export const SET_DATA_NODE = "SET_DATA_NODE";