export const ADD_RAW_DATA_NODE = "ADD_RAW_DATA_NODE";
export const ADD_JOINED_DATA_NODE = "ADD_JOINED_DATA_NODE";
export const ADD_TRANSFORMED_DATA_NODE = "ADD_TRANSFORMED_DATA_NODE";
export const ADD_JOINING_EDGE = "ADD_JOINING_EDGE";
export const ADD_TRANSFORMING_EDGE = "ADD_TRANSFORMING_EDGE";